version: '3'
#---------------------------------------------------------------------#
#                Homarr -  A homepage for your server.                #
#---------------------------------------------------------------------#
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - config:/app/data/configs
      - icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '7575:7575'
volumes:
  config:
  icons: