version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: always
    environment:
#      SIGNUPS_ALLOWED: 'false'
      ADMIN_TOKEN: 'RDVG3asKMg^&7mMgH7zo8r6j'
    ports:
      - '49153:80'
    volumes:
      - vaultwarden-data:/data/
volumes:
  vaultwarden-data: