version: '3.9'
services:
    dashy:
        image: 'lissy93/dashy:latest'
        restart: always
        container_name: dashy
        volumes:
            - 'conf:/app/public/'
        ports:
            - '8083:80'
volumes:
  conf: